### ISSUE TITLE
*ENTERING VIDEO DETAILS ISSUE* - [Date: 2024-06-26]

### ISSUE THREAD

**Issue by JennMayshiogie** [SingularityNET-Archive/archive-oracle#119]
### Issue Type

- [X] Bug/Defect
- [ ] Feature Request
- [ ] Template Issue (Is there an issue with the summary template you are using)
- [ ] Performance Issue
- [ ] Usability/Interface
- [ ] General Inquiry/Feedback
- [ ] Other

### Description

when I added and entried video details data according to date 10/5/2022 and 10/19/2022 the data became a duplication in both dates. Both information displayed was supposed to be different on video details.  

### Severity

High

### Workgroup

Deep Funding Town Hall

**Comment by Andre-Diamond** [comment]
I see both these dates had the info for the 21 March Town Hall video. I deleted all the duplicates. I noticed in the database that the wrong format of timestamps were added. That could have caused an error and not save the new data under the new date, hence the old March data still showing for those dates. Please only add this format of timestamps -

00:00 Intro
00:10 Breakout Room 1
1:56:09 Breakout Room 2
