### ISSUE TITLE
Working Docs section not working, cannot add any text or links - [Date: 2023-12-30]

### ISSUE THREAD

**Issue by Andre-Diamond** [SingularityNET-Archive/archive-oracle#22]
### Issue Type

- [ ] Bug/Defect
- [ ] Feature Request
- [ ] Template Issue
- [ ] Performance Issue
- [x] Usability/Interface
- [ ] Integration Issue
- [ ] Documentation/Help
- [ ] Security Concern
- [ ] General Inquiry/Feedback
- [ ] Other

### Description

Working Docs section not working - cannot add any text or links for Archive workgroup.

### Severity

High

### Workgroup

Archival Workgroup

**Comment by stephen-rowan** [comment]
Black text on black backgrounds makes it illegible.
Need to change to white text.

**Comment by Andre-Diamond** [comment]
Fixed issue here - https://github.com/SingularityNET-Archive/archive-oracle/commit/733f9acd330faebfc766964958cf5d4976b852bb

**Comment by whitevo** [comment]
![image](https://github.com/SingularityNET-Archive/archive-oracle/assets/10964567/d30141ae-7bdf-4cc2-aa57-61f50aa2dbc0)
I was not able to do that for first row in Knowledge Base WG
