### ISSUE TITLE
List of units, Workgroups and Guilds, incomplete

### ISSUE THREAD

**Issue by wkarshat** [SingularityNET-Archive/archive-oracle#26]
### Issue Type

- [ ] Bug/Defect
- [ ] Feature Request
- [ ] Template Issue
- [ ] Performance Issue
- [ ] Usability/Interface
- [ ] Integration Issue
- [ ] Documentation/Help
- [ ] Security Concern
- [x] General Inquiry/Feedback
- [ ] Other

### Description

List incomplete

### Severity

High

### Workgroup

All Workgroups

### Additional Context

Do the updates, including pulldown entry additions or deletions, require code changes, and in which file?

**Comment by Andre-Diamond** [comment]
Oh wait. For the workgroups some of it is in the code and some in the database. 

The changes in the code is to customize the order of agenda items for each workgroup. You'll see it in here -
https://github.com/SingularityNET-Archive/archive-oracle/blob/main/pages/submit-meeting-summary/index.tsx
