### ISSUE TITLE
List of Issue Types is excessive at 10, Labels do not match the process

### ISSUE THREAD

**Issue by wkarshat** [SingularityNET-Archive/archive-oracle#27]
### Issue Type

- [ ] Bug/Defect
- [x] Feature Request
- [ ] Template Issue
- [ ] Performance Issue
- [ ] Usability/Interface
- [ ] Integration Issue
- [ ] Documentation/Help
- [ ] Security Concern
- [x] General Inquiry/Feedback
- [ ] Other

### Description

List of Issue Types is excessive at 10, adding to the cognitive load up-front.
Unclear what Template or Integration reference.

Of a dozen Labels, only *tool-issue* has been used for the most recent dozen. Apparently the variety given does not have the resolution to match the actual process.

### Severity

Low

### Workgroup

All Workgroups

**Comment by Andre-Diamond** [comment]
I'll add an explanation next to template and remove some issues that could just go under bug.
The "tool-issue" was auto-assigned when people click on the link on the page. I'll rather change the labels manually everytime I start working on an issue to reflect the type of issue the person selected in the issue

**Comment by Andre-Diamond** [comment]
Made list shorter and I change the tags when I start working on the issue
