### ISSUE TITLE
Tagging baseline and versioning UI, Commit messages and cross-reference issues

### ISSUE THREAD

**Issue by wkarshat** [SingularityNET-Archive/archive-oracle#28]
### Issue Type

- [ ] Bug/Defect
- [ ] Feature Request
- [ ] Template Issue
- [ ] Performance Issue
- [ ] Usability/Interface
- [ ] Integration Issue
- [ ] Documentation/Help
- [ ] Security Concern
- [x] General Inquiry/Feedback
- [ ] Other

### Description

In order to support outside contributors, consider not pulling commits only into 'main'.

Consider connecting commits to Issues, which did not happen for just about every commit during 2024.
Consider labeling commits with reasons for the change, instead of the file affected, as in all too prevalent "Update testing_issue.yml"
 
Consider tagging baselines, each time a new version is rolled out for public access.
Consider adding version / tagging to the UI, to connect user feedback to codebase.

### Severity

Medium

### Workgroup

All Workgroups

**Comment by Andre-Diamond** [comment]
I didnt know how to connect issues to commits, but I figured it out, so will do it like that from now on.

I always add a reason for the commit when I work on the code. That specific commit ("Update testing_issue.yml") was for the issue template. Will add more  detail when I update that template again.

I also dont know how to do tagging, but will learn how to. And also add it to UI 👍

**Comment by Andre-Diamond** [comment]
I am still learning so the pulling only into main is the only way I know how. 
I will learn how to create and pull into other branches first. So that its easier for other people to contribute.

**Comment by Andre-Diamond** [comment]
Commits are now connected to Issues and Version tagging is implemented 👍
