### ISSUE TITLE
*Is it deleting meetings after the one that has just been submitted?* - [Date: 2024-01-25]

### ISSUE THREAD

**Issue by VanCardui** [SingularityNET-Archive/archive-oracle#31]
### Issue Type

- [X] Bug/Defect
- [ ] Feature Request
- [ ] Template Issue
- [ ] Performance Issue
- [ ] Usability/Interface
- [ ] Integration Issue
- [ ] Documentation/Help
- [ ] Security Concern
- [ ] General Inquiry/Feedback
- [ ] Other

### Description

If there's more than 1 meeting in there for a WG and you submit the earliest one, it seems to be deleting the ones after that

### Severity

High

### Workgroup

All Workgroups

**Comment by Andre-Diamond** [comment]
This is a temperary fix. It happened because we approved meetings in a weird sequence. If we approve them in the right sequnce we wont get this bug. I will work on a more permanant fix soon.
