### ISSUE TITLE
*Date not working* - [Date: 2024-01-29]

### ISSUE THREAD

**Issue by michealkizzy** [SingularityNET-Archive/archive-oracle#46]
### Issue Type

- [X] Bug/Defect
- [ ] Feature Request
- [ ] Template Issue (Is there an issue with the summary template you are using)
- [ ] Performance Issue
- [ ] Usability/Interface
- [ ] General Inquiry/Feedback
- [ ] Other

### Description

I noticed a bug in the summary tool, i couldn't add 1st of February 2024 in due date for action items.

### Severity

Medium

### Workgroup

Onboarding Workgroup

**Comment by Andre-Diamond** [comment]
Fixed over here - https://github.com/SingularityNET-Archive/archive-oracle/pull/41
