### ISSUE TITLE
PDF export of summary upon submission

### ISSUE THREAD

**Issue by rojokaboti** [SingularityNET-Archive/archive-oracle#5]
Would it be possible to get a pdf export of the summary made in the site once it's submitted.

**Comment by Andre-Diamond** [comment]
Yes, I imagine that can be quite useful for some users, I will look into adding this feature.

**Comment by rojokaboti** [comment]
Thanks, it would be great!

**Comment by Andre-Diamond** [comment]
Added feature here - https://github.com/SingularityNET-Archive/archive-oracle/commits/main/?since=2023-12-22&until=2023-12-24
