### ISSUE TITLE
Over populating Meeting Summary - [Date: 2024-02-09]

### ISSUE THREAD

**Issue by whitevo** [SingularityNET-Archive/archive-oracle#60]
### Issue Type

- [ ] Bug/Defect
- [X] Feature Request
- [ ] Template Issue (Is there an issue with the summary template you are using)
- [ ] Performance Issue
- [X] Usability/Interface
- [X] General Inquiry/Feedback
- [ ] Other

### Description

When I select new day for the meeting summary it keeps the list of previous meeting items.
Would like a button that clears all agenda, decision and action items.
There is a very small chance that they repeat, and even if they do, it doesn't outweigh the time it takes me to delete and clear or double check I have replaced old items with new items.

### Severity

Low

### Workgroup

Treasury Guild

**Comment by Andre-Diamond** [comment]
Fixed here - https://github.com/SingularityNET-Archive/archive-oracle/commit/12249e964390551acfd3b67f1f5729a8ddd15cbd
