### ISSUE TITLE
Sample Issue  - [Date: 2024-01-04]

### ISSUE THREAD

**Issue by stephen-rowan** [SingularityNET-Archive/archive-oracle#7]
### Issue Type

- [X] Bug/Defect
- [ ] Feature Request
- [ ] Template Issue
- [ ] Performance Issue
- [ ] Usability/Interface
- [ ] Integration Issue
- [ ] Documentation/Help
- [ ] Security Concern
- [ ] General Inquiry/Feedback

### Description

Sample description

### Severity

Medium

### Workgroup

Archive Workgroup

### Additional Context

etc

**Comment by Andre-Diamond** [comment]
Updates have been made and Issue template is working great
