### ISSUE TITLE
*Can we have a template for one off meetings * - [Date: 2024-02-13]

### ISSUE THREAD

**Issue by EseWilliams** [SingularityNET-Archive/archive-oracle#72]
### Issue Type

- [ ] Bug/Defect
- [ ] Feature Request
- [X] Template Issue (Is there an issue with the summary template you are using)
- [ ] Performance Issue
- [ ] Usability/Interface
- [ ] General Inquiry/Feedback
- [ ] Other

### Description

I think having meeting summaries in video formats or any format whatsoever could help in the future and we can use it for BTS and some marketing stunts and publicities

### Severity

Please select

### Workgroup

Please select

**Comment by Andre-Diamond** [comment]
Hi Ese, thank you for the feedback.

Next to date you can select one-off event if its a meeting for a specific workgroup
![image](https://github.com/SingularityNET-Archive/archive-oracle/assets/32074058/863c3339-ce39-447b-a055-ad17949f492b)

We do have an option for a one-off type of meeting for each workgroup. Is this what you want or do you mean a one-off meeting that is not related to any workgroup?

**Comment by Andre-Diamond** [comment]
I spoke to Vanessa. I'll be adding a one-off template soon 👍
